
STANDARD_TRAILER_DIMS = [
    {
        'name': "Standard 53' Dry-Van",
        'outer_width': 102,
        'outer_height': 13 * 12 + 6,
        'outer_length': 53 * 12,
        'inner_width': 98.5,
        'inner_height': 108,
        'inner_length': 47 * 12 + 6,
        'door_width': 94,
        'door_height': 102,
        'max_weight': 42500,
        'blockout_options': [7, 14],
    },
    {
        'name': "Standard 48' Dry-Van",
        'outer_width': 102,
        'outer_height': 13 * 12 + 6,
        'outer_length': 48 * 12,
        'inner_width': 98.5,
        'inner_height': 100.6,
        'inner_length': 47 * 12 + 6,
        'door_width': 98,
        'door_height': 100.6,
        'max_weight': 13500,
        'blockout_options': [7, 14],
    },
    {
        'name': "Standard 45' Dry-Van",
        'outer_width': 96,
        'outer_height': 13 * 12 + 6,
        'outer_length': 45 * 12,
        'inner_width': 93,
        'inner_height': 100.5,
        'inner_length': 44 * 12 + 1.5,
        'door_width': 87,
        'door_height': 98,
        'max_weight': 11900,
        'blockout_options': [8, 12, 15],
    },
    {
        'name': "Standard 43' Dry-Van",
        'outer_width': 96,
        'outer_height': 13 * 12,
        'outer_length': 43 * 12,
        'inner_width': 92.5,
        'inner_height': 100.5,
        'inner_length': 41 * 12 + 6,
        'door_width': 92,
        'door_height': 98,
        'max_weight': 11900,
        'blockout_options': [8, 12, 15],
    },
    {
        'name': "Standard 40' Dry-Van",
        'outer_width': 96,
        'outer_height': 12 * 12 + 6,
        'outer_length': 40 * 12,
        'inner_width': 92.5,
        'inner_height': 94.5,
        'inner_length': 39 * 12 + 6,
        'door_width': 92,
        'door_height': 92,
        'max_weight': 11300,
        'blockout_options': [8, 12, 15],
    },
    {
        'name': "28' Dry-Van, Pup - Roll Door",
        'outer_width': 102,
        'outer_height': 13 * 12 + 6,
        'outer_length': 28 * 12,
        'inner_width': 100,
        'inner_height': 107,
        'inner_length': 27 * 12 + 3,
        'door_width': 93,
        'door_height': 104,
        'max_weight': 22000,
        'blockout_options': [8, 10, 15],
    },
    {
        'name': "28' Dry-Van, Pup - Swing Door",
        'outer_width': 102,
        'outer_height': 13 * 12 + 6,
        'outer_length': 28 * 12,
        'inner_width': 99,
        'inner_height': 108,
        'inner_length': 27 * 12 + 3,
        'door_width': 99,
        'door_height': 108,
        'max_weight': 22000,
        'blockout_options': [9, 11],
    },
    {
        'name': "20' Shipping Container",
        'outer_width': 8 * 12,
        'outer_height': 8 * 12 + 6,
        'outer_length': 19 * 12 + 10,
        'inner_width': 7 * 12 + 8,
        'inner_height': 7 * 12 + 9,
        'inner_length': 19 * 12 + 4,
        'door_width': 7 * 12 + 8,
        'door_height': 7 * 12 + 6,
        'max_weight': 22000,
        'blockout_options': [9, 11],
    },
    {
        'name': "40' Shipping Container",
        'outer_width': 8 * 12,
        'outer_height': 8 * 12 + 6,
        'outer_length': 40 * 12,
        'inner_width': 7 * 12 + 8,
        'inner_height': 7 * 12 + 10,
        'inner_length': 39 * 12 + 6,
        'door_width': 7 * 12 + 8,
        'door_height': 7 * 12 + 6,
        'max_weight': 22000,
        'blockout_options': [9, 11],
    },
    {
        'name': "45' Shipping Container",
        'outer_width': 8 * 12,
        'outer_height': 9 * 12 + 6,
        'outer_length': 45 * 12,
        'inner_width': 7 * 12 + 8,
        'inner_height': 8 * 12 + 10,
        'inner_length': 44 * 12 + 6,
        'door_width': 7 * 12 + 8,
        'door_height': 8 * 12 + 6,
        'max_weight': 22000,
        'blockout_options': [9, 11],
    },
    {
        'name': "48' Shipping Container",
        'outer_width': 8 * 12 + 6,
        'outer_height': 9 * 12 + 6,
        'outer_length': 48 * 12,
        'inner_width': 8 * 12 + 2,
        'inner_height': 8 * 12 + 10,
        'inner_length': 47 * 12 + 6,
        'door_width': 7 * 12 + 8,
        'door_height': 8 * 12 + 6,
        'max_weight': 22000,
        'blockout_options': [9, 11],
    },
    {
        'name': "53' Shipping Container",
        'outer_width': 8 * 12 + 6,
        'outer_height': 9 * 12 + 6,
        'outer_length': 53 * 12,
        'inner_width': 8 * 12 + 2,
        'inner_height': 8 * 12 + 10,
        'inner_length': 52 * 12 + 3,
        'door_width': 7 * 12 + 8,
        'door_height': 8 * 12 + 6,
        'max_weight': 42500,
        'blockout_options': [9, 11],
    },
    {
        'name': "26' Flatbed Trailer",
        'outer_width': 96,
        'outer_height': None,
        'outer_length': 26 * 12,
        'inner_width': 96,
        'inner_height': 102,
        'inner_length': 26 * 12,
        'door_width': None,
        'door_height': None,
        'max_weight': 55000,
        'blockout_options': [9, 11],
    },
    {
        'name': "40' Flatbed Trailer",
        'outer_width': 96,
        'outer_height': None,
        'outer_length': 40 * 12,
        'inner_width': 96,
        'inner_height': 102,
        'inner_length': 40 * 12,
        'door_width': None,
        'door_height': None,
        'max_weight': 55000,
        'blockout_options': [9, 11],
    },
    {
        'name': "45' Flatbed Trailer",
        'outer_width': 102,
        'outer_height': None,
        'outer_length': 45 * 12,
        'inner_width': 102,
        'inner_height': 102,
        'inner_length': 45 * 12,
        'door_width': None,
        'door_height': None,
        'max_weight': 55000,
        'blockout_options': [9, 11],
    },
    {
        'name': "48' Flatbed Trailer",
        'outer_width': 102,
        'outer_height': None,
        'outer_length': 48 * 12,
        'inner_width': 102,
        'inner_height': 102,
        'inner_length': 48 * 12,
        'door_width': None,
        'door_height': None,
        'max_weight': 55000,
        'blockout_options': [9, 11],
    },
    {
        'name': "Small Straight Truck - 22'",
        'outer_width': 96,
        'outer_height': 8 * 12 + 6,
        'outer_length': 22 * 12,
        'inner_width': 92,
        'inner_height': 8 * 12,
        'inner_length': 21 * 12,
        'door_width': None,
        'door_height': None,
        'max_weight': 14000,
        'blockout_options': [9, 11],
    },
    {
        'name': "Large Straight Truck - 26'",
        'outer_width': 102,
        'outer_height': 8 * 12 + 6,
        'outer_length': 26 * 12,
        'inner_width': 96,
        'inner_height': 8 * 12,
        'inner_length': 25 * 12,
        'door_width': None,
        'door_height': None,
        'max_weight': 14000,
        'blockout_options': [9, 11],
    },
]

STANDARD_FREIGHT_PACKAGING_DIMS = [
    {
        'name': 'Standard 40"x48" Pallet',
        'length': 40,
        'width': 48,
    },
    {
        'name': 'Standard 42"x42" Pallet',
        'length': 42,
        'width': 42,
    },
    {
        'name': 'Standard 48"x48" Pallet',
        'length': 48,
        'width': 48,
    },
]

PACKING_BLOCKOUT = [
    {
        'low': 98,
        'high': 99,
        'blockout_options': [2, 7, 14]
    },
    {
        'low': 99,
        'high': 100,
        'blockout': [3, 9, 11]
    },
    {
        'low': 90,
        'high': 94,
        'blockout': [2, 3, 4, 8, 12, 15]
    },
    {
        'low': 100,
        'high': 104,
        'blockout': [2, 4, 5, 10, 15, 20]
    },
]
